In [53]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("gapminder_data_graphs.csv") ##stores in tabular structure
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

In [5]:
type(df)

pandas.DataFrame

In [8]:
type(df["country"])
##dataframe is matrix
##series id 1d, datafrma is stack of mulitple series

pandas.Series

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3675 entries, 0 to 3674
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      3675 non-null   str
 1   continent    3675 non-null   str
 2   year         3675 non-null   int64
 3   life_exp     3675 non-null   float64
 4   hdi_index    3563 non-null   float64
 5   co2_consump  3671 non-null   float64
 6   gdp          3633 non-null   float64
 7   services     3675 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 229.8 KB

In [12]:
##to print top five rows
df.head(10)
##to print bottom rows
df.tail()

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
3670,Zimbabwe,Africa,2014,58.0,0.547,0.881,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.881,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.771,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.845,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.850,1510.0,27.2

In [13]:
df.describe()

,year,life_exp,hdi_index,co2_consump,gdp,services
count,3675.000000,3675.000000,3563.000000,3671.000000,3633.000000,3675.000000
mean,2008.000000,69.849306,0.674864,4.712731,11966.053675,51.248705
std,6.056125,8.886563,0.164834,6.567435,17105.787953,18.312501
min,1998.000000,32.500000,0.255000,0.015900,238.000000,5.590000
25%,2003.000000,63.900000,0.537500,0.560500,1470.000000,37.600000
50%,2008.000000,71.700000,0.699000,2.250000,4280.000000,52.900000
75%,2013.000000,76.400000,0.805000,6.615000,13600.000000,65.700000
max,2018.000000,84.800000,0.956000,67.100000,105000.000000,88.500000

In [14]:
df.describe(include="object")

C:\Users\chitr\AppData\Local\Temp\ipykernel_11164\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

            country continent
count          3675      3675
unique          175         6
top     Afghanistan    Africa
freq             21      1071

In [15]:
#list of columns
df.columns

Index(['country', 'continent', 'year', 'life_exp', 'hdi_index', 'co2_consump',
       'gdp', 'services'],
      dtype='str')

In [ ]:
df.keys() ##pandas is specialised dictionary

Index(['country', 'continent', 'year', 'life_exp', 'hdi_index', 'co2_consump',
       'gdp', 'services'],
      dtype='str')

In [20]:
df[["country", "continent",]]

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
3670     Zimbabwe    Africa
3671     Zimbabwe    Africa
3672     Zimbabwe    Africa
3673     Zimbabwe    Africa
3674     Zimbabwe    Africa

[3675 rows x 2 columns]

In [21]:
##To list all unique contries
df["country"].unique

<bound method Series.unique of 0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: str>

In [26]:
df["country"].value_counts()
df["country"].value_counts().index

Index(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       ...
       'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='str', name='country', length=175)

In [31]:
##rename a columns
df.rename({"country":"Country"},axis=1,inplace=1)

In [45]:
df

,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
0,Asia,1998,53.3,0.344,0.0522,NaN,24.4,2051.3
1,Asia,1999,54.7,0.348,0.0402,NaN,24.6,2053.7
2,Asia,2000,54.7,0.350,0.0370,NaN,24.7,2054.7
3,Asia,2001,54.8,0.353,0.0376,NaN,24.7,2055.8
4,Asia,2002,55.5,0.384,0.0471,333.0,25.6,2057.5
...,...,...,...,...,...,...,...,...
3670,Africa,2014,58.0,0.547,0.8810,1440.0,25.4,2072.0
3671,Africa,2015,58.6,0.553,0.8810,1450.0,25.7,2073.6
3672,Africa,2016,59.2,0.558,0.7710,1430.0,26.1,2075.2
3673,Africa,2017,59.9,0.563,0.8450,1480.0,26.6,2076.9
3674,Africa,2018,60.6,0.569,0.8500,1510.0,27.2,2078.6

In [46]:
df.Country ##way of accesing not recomeed

AttributeError: 'DataFrame' object has no attribute 'Country'

In [42]:
# ##how to drop a perticular column
# df.drop("Country",axis=1, inplace=True)
# df

In [43]:
df["Total"] = df["year"] + df["life_exp"]

In [44]:
df

,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
0,Asia,1998,53.3,0.344,0.0522,NaN,24.4,2051.3
1,Asia,1999,54.7,0.348,0.0402,NaN,24.6,2053.7
2,Asia,2000,54.7,0.350,0.0370,NaN,24.7,2054.7
3,Asia,2001,54.8,0.353,0.0376,NaN,24.7,2055.8
4,Asia,2002,55.5,0.384,0.0471,333.0,25.6,2057.5
...,...,...,...,...,...,...,...,...
3670,Africa,2014,58.0,0.547,0.8810,1440.0,25.4,2072.0
3671,Africa,2015,58.6,0.553,0.8810,1450.0,25.7,2073.6
3672,Africa,2016,59.2,0.558,0.7710,1430.0,26.1,2075.2
3673,Africa,2017,59.9,0.563,0.8450,1480.0,26.6,2076.9
3674,Africa,2018,60.6,0.569,0.8500,1510.0,27.2,2078.6

In [48]:
##Row -- operations
se = df["year"]
se

0       1998
1       1999
2       2000
3       2001
4       2002
        ...
3670    2014
3671    2015
3672    2016
3673    2017
3674    2018
Name: year, Length: 3675, dtype: int64

In [51]:
##to get 6th row
se[2:4]

2    2000
3    2001
Name: year, dtype: int64

In [ ]:
se.index = np.arange(1,df.shape[0]+1,1) ##changed the indexx
se

1       1998
2       1999
3       2000
4       2001
5       2002
        ...
3671    2014
3672    2015
3673    2016
3674    2017
3675    2018
Name: year, Length: 3675, dtype: int64

In [ ]:
##implicet index are already present for example 0,1,2,3,4,5..
##explicet index are given from outside

In [57]:
data = pd.Series(["a","b","c"], index= [1,2,3])
data

1    a
2    b
3    c
dtype: str

In [ ]:
data[1] ##uses explicit indexing

'a'

In [ ]:
data[1:] ##slicing used implicit indexing

2    b
3    c
dtype: str