In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("gapminder_data_graphs.csv") ##stores in tabular structure
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

In [4]:
type(df)

pandas.DataFrame

In [8]:
type(df["country"])
##dataframe is matrix
##series id 1d, datafrma is stack of mulitple series

pandas.Series

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3675 entries, 0 to 3674
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      3675 non-null   str
 1   continent    3675 non-null   str
 2   year         3675 non-null   int64
 3   life_exp     3675 non-null   float64
 4   hdi_index    3563 non-null   float64
 5   co2_consump  3671 non-null   float64
 6   gdp          3633 non-null   float64
 7   services     3675 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 229.8 KB

In [6]:
##to print top five rows
df.head(10)
##to print bottom rows
df.tail()

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
3670,Zimbabwe,Africa,2014,58.0,0.547,0.881,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.881,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.771,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.845,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.850,1510.0,27.2

In [13]:
df.describe()

,year,life_exp,hdi_index,co2_consump,gdp,services
count,3675.000000,3675.000000,3563.000000,3671.000000,3633.000000,3675.000000
mean,2008.000000,69.849306,0.674864,4.712731,11966.053675,51.248705
std,6.056125,8.886563,0.164834,6.567435,17105.787953,18.312501
min,1998.000000,32.500000,0.255000,0.015900,238.000000,5.590000
25%,2003.000000,63.900000,0.537500,0.560500,1470.000000,37.600000
50%,2008.000000,71.700000,0.699000,2.250000,4280.000000,52.900000
75%,2013.000000,76.400000,0.805000,6.615000,13600.000000,65.700000
max,2018.000000,84.800000,0.956000,67.100000,105000.000000,88.500000

In [14]:
df.describe(include="object")

C:\Users\chitr\AppData\Local\Temp\ipykernel_11164\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

            country continent
count          3675      3675
unique          175         6
top     Afghanistan    Africa
freq             21      1071

In [15]:
#list of columns
df.columns

Index(['country', 'continent', 'year', 'life_exp', 'hdi_index', 'co2_consump',
       'gdp', 'services'],
      dtype='str')

In [ ]:
df.keys() ##pandas is specialised dictionary

Index(['country', 'continent', 'year', 'life_exp', 'hdi_index', 'co2_consump',
       'gdp', 'services'],
      dtype='str')

In [ ]:
df[["country", "continent"]]

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
3670     Zimbabwe    Africa
3671     Zimbabwe    Africa
3672     Zimbabwe    Africa
3673     Zimbabwe    Africa
3674     Zimbabwe    Africa

[3675 rows x 2 columns]

In [21]:
##To list all unique contries
df["country"].unique

<bound method Series.unique of 0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: str>

In [26]:
df["country"].value_counts()
df["country"].value_counts().index

Index(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       ...
       'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='str', name='country', length=175)

In [7]:
##rename a columns
df.rename({"country":"Country"},axis=1,inplace=1)

In [45]:
df

,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
0,Asia,1998,53.3,0.344,0.0522,NaN,24.4,2051.3
1,Asia,1999,54.7,0.348,0.0402,NaN,24.6,2053.7
2,Asia,2000,54.7,0.350,0.0370,NaN,24.7,2054.7
3,Asia,2001,54.8,0.353,0.0376,NaN,24.7,2055.8
4,Asia,2002,55.5,0.384,0.0471,333.0,25.6,2057.5
...,...,...,...,...,...,...,...,...
3670,Africa,2014,58.0,0.547,0.8810,1440.0,25.4,2072.0
3671,Africa,2015,58.6,0.553,0.8810,1450.0,25.7,2073.6
3672,Africa,2016,59.2,0.558,0.7710,1430.0,26.1,2075.2
3673,Africa,2017,59.9,0.563,0.8450,1480.0,26.6,2076.9
3674,Africa,2018,60.6,0.569,0.8500,1510.0,27.2,2078.6

In [8]:
df.Country ##way of accesing not recomeed

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: Country, Length: 3675, dtype: str

In [42]:
# ##how to drop a perticular column
# df.drop("Country",axis=1, inplace=True)
# df

In [9]:
df["Total"] = df["year"] + df["life_exp"]

In [44]:
df

,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
0,Asia,1998,53.3,0.344,0.0522,NaN,24.4,2051.3
1,Asia,1999,54.7,0.348,0.0402,NaN,24.6,2053.7
2,Asia,2000,54.7,0.350,0.0370,NaN,24.7,2054.7
3,Asia,2001,54.8,0.353,0.0376,NaN,24.7,2055.8
4,Asia,2002,55.5,0.384,0.0471,333.0,25.6,2057.5
...,...,...,...,...,...,...,...,...
3670,Africa,2014,58.0,0.547,0.8810,1440.0,25.4,2072.0
3671,Africa,2015,58.6,0.553,0.8810,1450.0,25.7,2073.6
3672,Africa,2016,59.2,0.558,0.7710,1430.0,26.1,2075.2
3673,Africa,2017,59.9,0.563,0.8450,1480.0,26.6,2076.9
3674,Africa,2018,60.6,0.569,0.8500,1510.0,27.2,2078.6

In [10]:
##Row -- operations
se = df["year"]
se

0       1998
1       1999
2       2000
3       2001
4       2002
        ...
3670    2014
3671    2015
3672    2016
3673    2017
3674    2018
Name: year, Length: 3675, dtype: int64

In [11]:
##to get 6th row
se[2:4]

2    2000
3    2001
Name: year, dtype: int64

In [12]:
se.index = np.arange(1,df.shape[0]+1,1) ##changed the indexx
se

1       1998
2       1999
3       2000
4       2001
5       2002
        ...
3671    2014
3672    2015
3673    2016
3674    2017
3675    2018
Name: year, Length: 3675, dtype: int64

In [ ]:
##implicet index are already present for example 0,1,2,3,4,5..
##explicet index are given from outside

In [13]:
data = pd.Series(["a","b","c"], index= [1,2,3])
data

1    a
2    b
3    c
dtype: str

In [14]:
data[1] ##uses explicit indexing

'a'

In [15]:
data[1:] ##slicing used implicit indexing

2    b
3    c
dtype: str

In [17]:
##loc-- works with explicit indexes/labels
##iloc--works with implicit indesed/positional indexes

df.loc[[1,10,100]]

,Country,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6,2053.7
10,Afghanistan,Asia,2008,59.2,0.447,0.1520,415.0,28.2,2067.2
100,Argentina,South America,2014,76.5,0.836,4.5600,13600.0,75.3,2090.5

In [ ]:
df.iloc[-1]  ##inpyhon -1 iss

Country        Zimbabwe
continent        Africa
year               2018
life_exp           60.6
hdi_index         0.569
co2_consump        0.85
gdp              1510.0
services           27.2
Total            2078.6
Name: 3674, dtype: object

In [ ]:
temp = df.set_index("year") ##setting year as label

In [ ]:
temp

,Country,continent,life_exp,hdi_index,co2_consump,gdp,services,Total
year,,,,,,,,
1998,Afghanistan,Asia,53.3,0.344,0.0522,NaN,24.4,2051.3
1999,Afghanistan,Asia,54.7,0.348,0.0402,NaN,24.6,2053.7
2000,Afghanistan,Asia,54.7,0.350,0.0370,NaN,24.7,2054.7
2001,Afghanistan,Asia,54.8,0.353,0.0376,NaN,24.7,2055.8
2002,Afghanistan,Asia,55.5,0.384,0.0471,333.0,25.6,2057.5
...,...,...,...,...,...,...,...,...
2014,Zimbabwe,Africa,58.0,0.547,0.8810,1440.0,25.4,2072.0
2015,Zimbabwe,Africa,58.6,0.553,0.8810,1450.0,25.7,2073.6
2016,Zimbabwe,Africa,59.2,0.558,0.7710,1430.0,26.1,2075.2
2017,Zimbabwe,Africa,59.9,0.563,0.8450,1480.0,26.6,2076.9
2018,Zimbabwe,Africa,60.6,0.569,0.8500,1510.0,27.2,2078.6

In [21]:
temp["gdp"]

year
1998       NaN
1999       NaN
2000       NaN
2001       NaN
2002     333.0
         ...
2014    1440.0
2015    1450.0
2016    1430.0
2017    1480.0
2018    1510.0
Name: gdp, Length: 3675, dtype: float64

In [22]:
d = {"Country":"India","year":2009, "life_exp":37.08, "continent":"Asia", "gdp":100}

In [27]:
df =pd.concat([df,pd.DataFrame([d])], ignore_index = True)

In [ ]:
df ##pd.concar([df,pd.dataframe([d])])

,Country,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
0,Afghanistan,Asia,1998,53.30,0.344,0.0522,NaN,24.4,2051.3
1,Afghanistan,Asia,1999,54.70,0.348,0.0402,NaN,24.6,2053.7
2,Afghanistan,Asia,2000,54.70,0.350,0.0370,NaN,24.7,2054.7
3,Afghanistan,Asia,2001,54.80,0.353,0.0376,NaN,24.7,2055.8
4,Afghanistan,Asia,2002,55.50,0.384,0.0471,333.0,25.6,2057.5
...,...,...,...,...,...,...,...,...,...
3671,Zimbabwe,Africa,2015,58.60,0.553,0.8810,1450.0,25.7,2073.6
3672,Zimbabwe,Africa,2016,59.20,0.558,0.7710,1430.0,26.1,2075.2
3673,Zimbabwe,Africa,2017,59.90,0.563,0.8450,1480.0,26.6,2076.9
3674,Zimbabwe,Africa,2018,60.60,0.569,0.8500,1510.0,27.2,2078.6
3675,India,Asia,2009,37.08,NaN,NaN,100.0,NaN,NaN

In [34]:
df.loc[len(df.index)] = [
    "India",
    2025,
    70.5,
    0.75,
    2.5,
    3000,
    55.2,
    3677,
    "Asia"
]

In [35]:
df

,Country,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
0,Afghanistan,Asia,1998.0,53.30,0.344,0.0522,NaN,24.4,2051.3
1,Afghanistan,Asia,1999.0,54.70,0.348,0.0402,NaN,24.6,2053.7
2,Afghanistan,Asia,2000.0,54.70,0.350,0.0370,NaN,24.7,2054.7
3,Afghanistan,Asia,2001.0,54.80,0.353,0.0376,NaN,24.7,2055.8
4,Afghanistan,Asia,2002.0,55.50,0.384,0.0471,333.0,25.6,2057.5
...,...,...,...,...,...,...,...,...,...
3672,Zimbabwe,Africa,2016.0,59.20,0.558,0.7710,1430.0,26.1,2075.2
3673,Zimbabwe,Africa,2017.0,59.90,0.563,0.8450,1480.0,26.6,2076.9
3674,Zimbabwe,Africa,2018.0,60.60,0.569,0.8500,1510.0,27.2,2078.6
3675,India,Asia,2009.0,37.08,NaN,NaN,100.0,NaN,NaN
3676,India,2025,70.5,0.75,2.500,3000.0000,55.2,3677.0,Asia

In [36]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3672    False
3673    False
3674    False
3675    False
3676    False
Length: 3677, dtype: bool

In [38]:
df.loc[df.duplicated()]

Empty DataFrame
Columns: [Country, continent, year, life_exp, hdi_index, co2_consump, gdp, services, Total]
Index: []

In [43]:
##drop a row with label
df.drop(1,axis = 0,inplace=True)

In [41]:
df.iloc[1]

Country        Afghanistan
continent             Asia
year                1999.0
life_exp              54.7
hdi_index            0.348
co2_consump         0.0402
gdp                    NaN
services              24.6
Total               2053.7
Name: 1, dtype: object

In [44]:
df.loc[1]

KeyError: 1

In [ ]:
df.iloc[1:5,0:4] ##uapr +1 kar diye the na

       Country continent    year  life_exp
2  Afghanistan      Asia  2000.0      54.7
3  Afghanistan      Asia  2001.0      54.8
4  Afghanistan      Asia  2002.0      55.5
5  Afghanistan      Asia  2003.0      56.5

In [ ]:
df.loc[1:5,0:4] ##actual columns are counteyr.................

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [47]:
df.loc[1:5,"year":"life_exp"]

     year  life_exp
2  2000.0      54.7
3  2001.0      54.8
4  2002.0      55.5
5  2003.0      56.5

In [48]:
df["life_exp"].mean()

np.float64(69.82571545157779)

In [50]:
df["life_exp"].sum()

np.float64(256679.33)

In [52]:
df.sort_values(["year"],ascending=False)

,Country,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
1385,Guinea-Bissau,Africa,2018.0,60.30,0.472,0.1810,638.0,30.3,2078.3
3653,Zambia,Africa,2018.0,62.50,0.582,0.3020,1370.0,39.3,2080.5
3611,Vietnam,Asia,2018.0,74.30,0.700,2.1600,2460.0,34.7,2092.3
3674,Zimbabwe,Africa,2018.0,60.60,0.569,0.8500,1510.0,27.2,2078.6
41,Albania,Europe,2018.0,78.40,0.792,1.5900,4430.0,43.0,2096.4
...,...,...,...,...,...,...,...,...,...
3612,Yemen,Asia,1998.0,62.50,0.431,0.7340,2290.0,41.1,2060.5
3633,Zambia,Africa,1998.0,45.50,0.416,0.2310,751.0,23.0,2043.5
0,Afghanistan,Asia,1998.0,53.30,0.344,0.0522,NaN,24.4,2051.3
21,Albania,Europe,1998.0,74.80,0.655,0.5630,1600.0,33.0,2072.8
3676,India,2025,70.5,0.75,2.500,3000.0000,55.2,3677.0,Asia

In [55]:
df.sort_values(["year","life_exp"],ascending=[False, True])

,Country,continent,year,life_exp,hdi_index,co2_consump,gdp,services,Total
1889,Lesotho,Africa,2018.0,51.40,0.522,1.2600,1110.0,41.6,2069.4
650,Central African Republic,Africa,2018.0,51.50,0.395,0.0651,413.0,23.4,2069.5
1112,Eswatini,Africa,2018.0,57.80,0.605,1.0600,3780.0,63.8,2075.8
2267,Mozambique,Africa,2018.0,57.90,0.452,0.2810,603.0,21.0,2075.9
2981,Solomon Islands,Oceania,2018.0,59.00,0.564,0.2730,2320.0,50.5,2077.0
...,...,...,...,...,...,...,...,...,...
1449,"Hong Kong, China",Asia,1998.0,79.60,0.820,6.0700,24900.0,77.2,2077.6
3171,Sweden,Europe,1998.0,79.60,0.894,6.6200,37700.0,71.1,2077.6
3192,Switzerland,Europe,1998.0,79.90,0.882,6.3000,70700.0,70.2,2077.9
1680,Japan,Asia,1998.0,81.00,0.849,9.4900,30800.0,62.5,2079.0
3676,India,2025,70.5,0.75,2.500,3000.0000,55.2,3677.0,Asia

In [56]:
##how to create dataframe from scratch

pd.Series([10,20,30], index=["a","b","c"])

a    10
b    20
c    30
dtype: int64

In [62]:
##row oriented
pd.DataFrame([[10,20],[30,40]], columns=["A","B"], index=["h","h"])

    A   B
h  10  20
h  30  40

In [ ]:
pd.DataFrame({"A":[10,20], "B":[20,40]}) ###keys in datafrmas are columns

    A   B
0  10  20
1  20  40

In [2]:
pd.Series(["A","B"], index= ["a","b"])

a    A
b    B
dtype: str